language: objective-c
osx_image: xcode8
xcode_workspace: NetworkActivityIndicatorManager.xcworkspace
xcode_scheme: NetworkActivityIndicatorManager
xcode_sdk: iphonesimulator9.3
script:
    - gem install xcpretty
    - carthage bootstrap --platform iOS --use-submodules
    - xcodebuild -workspace NetworkActivityIndicatorManager.xcworkspace -scheme NetworkActivityIndicatorManager -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6s,OS=10.0' ONLY_ACTIVE_ARCH=NO clean test | xcpretty
