language: objective-c
osx_image: xcode7.2
xcode_workspace: NetworkActivityIndicatorManager.xcworkspace
xcode_scheme: NetworkActivityIndicatorManager
xcode_sdk: iphonesimulator9.2
before_install:
        - brew update
        - brew install xctool
script:
        - carthage bootstrap --platform iOS
        - xctool -workspace NetworkActivityIndicatorManager.xcworkspace -scheme NetworkActivityIndicatorManager -sdk iphonesimulator9.2 -destination 'platform=iOS Simulator,name=iPhone 6s' ONLY_ACTIVE_ARCH=NO clean test
